import { PageHeader } from "@/components/page-header";

export default function SettingsPage() {
  const publicEnabled = process.env.ENABLE_PUBLIC_PRICE_CHECKS === "true";
  const interval = Math.max(60_000, Number(process.env.SCRAPER_MIN_INTERVAL_MS ?? 60_000));
  return <><PageHeader eyebrow="Yönetişim" title="Ayarlar ve Güvenlik" description="OdaRadar yalnızca kurum içi gelir yönetimi analizi için, izinli ve herkese açık fiyatları kontrollü biçimde gözlemlemek üzere tasarlanmıştır." />
    <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><section className="card p-6"><h2 className="text-lg font-bold">Kullanım ilkeleri</h2><div className="mt-5 space-y-4 text-sm leading-relaxed text-black/65"><Rule title="Yalnızca açık ve izinli sayfalar">Her kaynağın robots.txt dosyasını ve kullanım koşullarını kontrol edin. Kullanıcı, ilgili sitenin koşullarına uymaktan sorumludur.</Rule><Rule title="Erişim kontrollerine saygı">CAPTCHA, giriş, ödeme duvarı, üye fiyatı veya anti-bot ekranı görülürse kontrol durur ve “engellendi” olarak kaydedilir.</Rule><Rule title="Düşük frekans">Aynı public kaynağa istekler arasında en az 60 saniye vardır ve varsayılan eşzamanlı tarayıcı sayfası birdir.</Rule><Rule title="Kişisel veri yok">Misafir veya çalışan kişisel verisi toplanmaz. Yalnızca herkese görünür konaklama fiyatı ve arama bağlamı saklanır.</Rule><Rule title="Agresif teknikler yok">Proxy rotasyonu, sahte giriş, CAPTCHA çözme veya erişim kısıtı aşma uygulanmaz.</Rule></div></section>
      <aside className="space-y-5"><div className="card p-6"><div className="flex items-center justify-between"><div><p className="label">ENABLE_PUBLIC_PRICE_CHECKS</p><p className="font-bold">Public kontroller</p></div><span className={`pill ${publicEnabled ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{publicEnabled ? "Açık" : "Kapalı"}</span></div><p className="mt-4 text-xs leading-relaxed text-black/50">Public kontrolleri açmak için <code>.env</code> dosyasına aşağıdaki değeri ekleyip uygulamayı yeniden başlatın. Veritabanı ayarı erişim yetkisi vermez.</p><code className="mt-3 block rounded-lg bg-black/[0.04] px-3 py-2 text-xs">ENABLE_PUBLIC_PRICE_CHECKS=true</code></div>
        <div className="card p-6"><p className="label">Hız sınırı</p><p className="text-2xl font-bold">{Math.round(interval / 1000)} saniye</p><p className="mt-1 text-xs text-black/50">Aynı public kaynağa istekler arasında minimum süre</p><hr className="my-5 border-black/5"/><p className="label">Maksimum eşzamanlılık</p><p className="text-2xl font-bold">1 sayfa</p></div>
        <div className="rounded-2xl bg-[#172126] p-6 text-white"><p className="text-sm font-bold">Public kontrol sınırları</p><ul className="mt-3 space-y-2 text-xs text-white/65"><li>• CAPTCHA bypass yok</li><li>• Login veya üye fiyatı yok</li><li>• Erişim engellenirse işlem durur</li><li>• Site şartlarına uyma sorumluluğu kullanıcıdadır</li></ul><p className="mt-4 text-xs leading-relaxed text-white/50">Bir kaynağın izin durumu belirsizse public kontrolü açmayın; manuel gözlem kullanın.</p></div></aside>
    </div>
  </>;
}
function Rule({ title, children }: { title: string; children: React.ReactNode }) { return <div className="flex gap-3"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-teal-50 text-xs font-bold text-teal-700">✓</span><p><b className="block text-ink">{title}</b>{children}</p></div>; }
