import { ManualObservationForm } from "@/components/manual-observation-form";
import { PageHeader } from "@/components/page-header";
import { db } from "@/lib/db";
import { formatDate, formatDateTime, formatMoney, toNumber } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function ObservationsPage({ searchParams }: { searchParams: Promise<{ competitorId?: string; profileId?: string; status?: string }> }) {
  const filters = await searchParams; const status = ["success", "unavailable", "blocked", "error"].includes(filters.status ?? "") ? filters.status as "success" | "unavailable" | "blocked" | "error" : undefined;
  const [observations, competitors, profiles] = await Promise.all([
    db.priceObservation.findMany({ where: { competitorId: filters.competitorId || undefined, profileId: filters.profileId || undefined, status }, orderBy: { observedAt: "desc" }, take: 200, include: { competitor: { select: { name: true } }, profile: { select: { name: true } } } }),
    db.competitor.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }), db.searchProfile.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }),
  ]);
  return <><PageHeader eyebrow="Geçmiş" title="Fiyat Gözlemleri" description="Her gözlem kaynak, arama bağlamı, fiyat ve sonuç durumuyla birlikte saklanır." action={<ManualObservationForm competitors={competitors} profiles={profiles} />} />
    <form className="card mb-5 grid gap-3 p-4 sm:grid-cols-4"><select className="input" name="competitorId" defaultValue={filters.competitorId}><option value="">Tüm rakipler</option>{competitors.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="input" name="profileId" defaultValue={filters.profileId}><option value="">Tüm profiller</option>{profiles.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="input" name="status" defaultValue={filters.status}><option value="">Tüm durumlar</option><option value="success">Başarılı</option><option value="unavailable">Müsait değil</option><option value="blocked">Engellendi</option><option value="error">Hata</option></select><button className="btn-secondary">Filtrele</button></form>
    <div className="card overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="border-b border-black/5 bg-black/[0.02] text-[10px] uppercase tracking-widest text-black/45"><tr><th className="px-5 py-3">Rakip / Profil</th><th className="px-4 py-3">Konaklama</th><th className="px-4 py-3">Oda</th><th className="px-4 py-3">Fiyat</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3">Gözlem zamanı</th></tr></thead><tbody className="divide-y divide-black/5">{observations.map((item) => <tr key={item.id} className="align-top"><td className="px-5 py-4"><b>{item.competitor.name}</b><span className="mt-1 block text-xs text-black/45">{item.profile.name} · {item.source}</span></td><td className="px-4 py-4">{formatDate(item.checkIn)} → {formatDate(item.checkOut)}<span className="mt-1 block text-xs text-black/45">{item.adults} yetişkin, {item.children} çocuk</span></td><td className="px-4 py-4">{item.roomName ?? "—"}<span className="mt-1 block max-w-64 truncate text-xs text-black/45">{item.boardType ?? item.availabilityText ?? "—"}</span></td><td className="px-4 py-4 font-bold">{item.priceAmount ? formatMoney(toNumber(item.priceAmount)!, item.currency) : "—"}</td><td className="px-4 py-4"><Status value={item.status} />{item.status === "unavailable" && item.availabilityText && <span className="mt-2 block max-w-80 text-xs leading-relaxed text-amber-700">{item.availabilityText}</span>}{item.errorMessage && <span title={item.errorMessage} className="mt-1 block max-w-40 truncate text-[10px] text-red-500">{item.errorMessage}</span>}</td><td className="px-4 py-4 text-xs text-black/55">{formatDateTime(item.observedAt)}</td></tr>)}{!observations.length && <tr><td colSpan={6} className="p-10 text-center text-black/45">Filtreye uygun gözlem bulunamadı.</td></tr>}</tbody></table></div>
  </>;
}
function Status({ value }: { value: string }) { const map: Record<string, [string, string]> = { success: ["Başarılı", "bg-emerald-50 text-emerald-700"], unavailable: ["Müsait değil", "bg-amber-50 text-amber-700"], blocked: ["Engellendi", "bg-red-50 text-red-700"], error: ["Hata", "bg-red-50 text-red-700"] }; const item = map[value] ?? [value, "bg-black/5"]; return <span className={`pill ${item[1]}`}>{item[0]}</span>; }
